collections:
    "v":
        index: $live
        templates:
            banner: templates/banner.rewriter
            error: templates/error.rewriter
            head_insert: templates/head_insert.rewriter

            index: template/index.html
            search: template/search.html
            query: template/query.html

framed_replay: false
